### PR TITLE
Travis NPM Deployment

### PR DESCRIPTION
**Pull request by Boserr**
I changed the webpack and docs stages to act on the new 'stable' branch I made, I also made the NPM deploy stage, you can add the email and token (find how to generate one [here](https://docs.npmjs.com/getting-started/working_with_tokens)

### CODE REVIEW

**Comment by ickerio** [comment]
Merge once I've added the token to prevent anything from breaking

**Comment by Boserr** [comment]
Yeah I guess we can

**Comment by ickerio** [comment]
@Boserr Don't want to mess anything up. Is this right when releasing to stable? Not an expert at git so just wanted to run it past you. Cheers!
```
git pull 
git checkout stable
git merge master
git tag -a v3.0 -m "New stable release version 3.0"
git push origin stable
```

**Comment by Boserr** [comment]
When you’re pushing a new tag make sure you do
`git push origin stable —tags`

That makes sure that GitHub gets the new tag
But yeah other than that, that’s right

**Comment by Boserr** [comment]
I noticed we’re at 3.5.4 but there’s no tag on master, just make sure you push to master again (from your master branch) with
`git push —tags`
Before you merge to stable as well

**Comment by Boserr** [comment]
My bad, use
    `git push --follow-tags`

This pushes the commits and the tags at the same time

**Pull request merged**
