### PR TITLE
Patch travis

### PR DESCRIPTION
**Pull request by jamesc2400**
Just some improvements to the Travis config
I guess the builds won’t work on PRs as they need an API key..

### CODE REVIEW

**Comment by jamesc2400** [comment]
No it shouldn’t do, it just stop it from testing that branch (which always fail).

**Comment by jamesc2400** [comment]
Can confirm that when it builds on my fork it does the Webpack release stage just fine 👍

**Comment by ickerio** [comment]
Awesome, thanks for your help!

**Comment by jamesc2400** [comment]
@ickerio Just thought I'd mention, testing API wrappers is difficult, as you rely on the external API being fault proof for your tests to pass. So it's good to save a range of different responses and test on those, I'm working on something right now.

**Comment by ickerio** [comment]
Yeah, I haven't really delved into the whole travis testing stuff thoroughly. And thanks for all your help on this stuff, really appreciated 👍

**Pull request merged**
