### PR TITLE
Testing Suite (WIP)

### PR DESCRIPTION
**Pull request by Boserr**
So I’ve started some work on some more testing scripts, it’s not complete yet, just thought I’d open this PR so I can get your thoughts. A good test suite will cover all the features of the API and can be helpful in that it detects unintentional changes.

From my research, testing an API wrapper on the actual live API is a bad idea. Apparently it’s better to save some responses from the live API into JSON files and inject that data into the wrapper that way, and you can test on it with a variety of different scenarios.
Obviously it’s much more complicated doing it this way, and it’s much easier to write tests to act on the live API, I might just do that. But the builds will fail if the API goes down, what are your thoughts?

Here are the things that came with it:

- Mocha and Chai as dev dependencies, these are used for the testing suite

- Put some of the error messages into a Constants file, so if they need to be changed it is reflected in the main code base as well as the testing script. Did the same for the default shard.

### CODE REVIEW

**Comment by Boserr** [comment]
Can I also suggest that we create a new branch called ‘develop’ which gets all the latest changes? Imo the master branch should only have production ready code, when you are ready to make a new release you can merge the develop branch into master.

http://nvie.com/posts/a-successful-git-branching-model/ This is a good development model that I like to follow

**Comment by ickerio** [comment]
Wow, this is awesome! Thanks for all your effort on this. Just read through everything and looks really good! 

I definitely agree on having seperate branches. One I have seen quite a lot and I think I'll be adopting is having a `master` which in your case is equivalent to `develop` and a `stable` which is the latest stable version pushed to npm. 

You've got the WIP still so I'm assuming you don't want me to merge it yet. If you'd like I can make you a contributor so you get push access.

**Comment by Boserr** [comment]
Yeah that sounds good, you could even incorporate a deploy process on the stable branch in Travis.

**Comment by Boserr** [comment]
I'll close this PR for now and make a new one for the branch on this repo

**Pull request closed without merging**
